POST http://localhost:3800/api/v1/auth/admin-register HTTP/1.1
content-type: application/json

{
    "name": "Gboun Marvellous",
    "username": "lankiman",
    "official_email": "marvellousgboun@gmail.com",
    "personal_email": "marvellousgboun@gmail.com",
    "password": "@JohnDoe123",
    "phoneNumber": "07058803416",
    "authorizationLevel": "owner"
}

