import { config } from 'dotenv';

config({ path: `.env` });

export const {
  NODE_ENV, PORT, DB_URI,
  DB_HOST, DB_PORT, DB_NAME,
  DB_TYPE, HOST, DB_USER, DB_PASSWORD
  , LOG_FORMAT, LOG_DIR,
  JWT_SECRET_KEY, JWT_EXPIRATION_HOURS,
  JWT_ISSUER, ADMIN_FIRST_NAME, ADMIN_LAST_NAME, ADMIN_GENDER, ADMIN_ROLE,
  ADMIN_EMAIL, ADMIN_PHONE, ADMIN_PASSWORD,
  SENDGRID_API_KEY, SENDER_EMAIL, SENDCHAMP_LIVEURL,
  SENDCHAMP_SENDER, SENDCHAMP_APIKEY,
  SMTP_HOSTNAME, SMTP_USERNAME, SMTP_PASSWORD, SMTP_PORT, SMTP_SECURE,
  APP_NAME, APP_URL, APP_LOGO, APP_EMAIL, BANK_NAME, BANK_CODE, COIN_MARKET_API_KEY, COIN_MARKET_API,
  USER_EMAIL, USER_PASS, CLIENT_ID, CLIENT_SECRET, REFRESH_TOKEN, ACCESS_TOKEN, TWILIO_NUMBER, TWILIO_SID, TWILIO_TOKEN
} = process.env;
