import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1744668722400 implements MigrationInterface {
    name = 'InitialMigration1744668722400'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "yenreach"."local_governments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "num_id" integer NOT NULL, "name" character varying(1000) NOT NULL, "state_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_67f8d73eafbbb52a527c8e07e44" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "yenreach"."states" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "num_id" integer NOT NULL, "name" character varying(100) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_09ab30ca0975c02656483265f4f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "yenreach"."product_photos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "media_path" character varying(500) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_0586e8a3f1766827efaf0ee3943" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ef0be6cd13fe604b1e7ae5987b" ON "yenreach"."product_photos" ("product_id") `);
        await queryRunner.query(`CREATE TYPE "yenreach"."products_status_enum" AS ENUM('Available', 'OutOfStock', 'Discontinued')`);
        await queryRunner.query(`CREATE TABLE "yenreach"."products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "product_string" character varying(255) NOT NULL, "name" character varying(255) NOT NULL, "description" text NOT NULL, "quantity" integer NOT NULL, "price" integer NOT NULL, "color" character varying(255) NOT NULL, "safety_tip" text NOT NULL, "status" "yenreach"."products_status_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0806c755e0aca124e67c0cf6d7" ON "yenreach"."products" ("id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6706ea94d32be01f9272ccc351" ON "yenreach"."products" ("business_id") `);
        await queryRunner.query(`CREATE TABLE "yenreach"."product_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "category_id" uuid NOT NULL, "product_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_7069dac60d88408eca56fdc9e0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "yenreach"."categories_category_type_enum" AS ENUM('business', 'product')`);
        await queryRunner.query(`CREATE TABLE "yenreach"."categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "parent_category_id" uuid, "verify_string" character varying NOT NULL, "category" character varying(100) NOT NULL, "category_type" "yenreach"."categories_category_type_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "yenreach"."business_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "category_id" uuid NOT NULL, "business_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_d10a707dfd0ca189233999204e5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "yenreach"."business_photos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "media_path" character varying(500) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_6faca94139d2328fe3b4bf575f6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8f15fc3faea20619b61ad9d0df" ON "yenreach"."business_photos" ("business_id") `);
        await queryRunner.query(`CREATE TABLE "yenreach"."business_reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "user_id" uuid NOT NULL, "review" text NOT NULL, "star" smallint NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_bed5317b9c51c138b04219e85b4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_86f38bc84d82e2c985d2afe128" ON "yenreach"."business_reviews" ("business_id") `);
        await queryRunner.query(`CREATE TABLE "yenreach"."business_videos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "media_path" character varying(500) NOT NULL, "platform" character varying(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_85805025611c8014ade262f4542" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_39550c1d974cf4a9fcf15efb2e" ON "yenreach"."business_videos" ("business_id") `);
        await queryRunner.query(`CREATE TABLE "yenreach"."business_working_hours" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "days" character varying(255) NOT NULL, "opening_time" character varying(255) NOT NULL, "closing_time" character varying(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_3859674f52675aabf72d0f8bd60" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ac12abaae569edd6bf385962ef" ON "yenreach"."business_working_hours" ("business_id") `);
        await queryRunner.query(`CREATE TYPE "yenreach"."businesses_registration_status_enum" AS ENUM('incomplete', 'pending', 'approved')`);
        await queryRunner.query(`CREATE TABLE "yenreach"."businesses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "verify_string" character varying(255) NOT NULL, "name" character varying(255) NOT NULL, "description" text NOT NULL, "user_string" character varying(255) NOT NULL, "user_id" uuid, "subscription_string" character varying(255), "address" character varying(500) NOT NULL, "town" character varying(500) NOT NULL, "lga_id" uuid, "state_id" uuid, "phone_number" character varying(100) NOT NULL, "whatsapp" character varying(100) NOT NULL, "email" character varying(500) NOT NULL, "website" character varying(500), "facebook_link" character varying(500), "twitter_link" character varying(500), "instagram_link" character varying(500), "youtube_link" character varying(500), "linkedin_link" character varying(500), "curriculum_vitae" character varying, "experience" integer NOT NULL, "month_started" character varying(100) NOT NULL, "year_started" character varying(100) NOT NULL, "profile_img" character varying(250), "cover_img" character varying(250), "registration_status" "yenreach"."businesses_registration_status_enum" NOT NULL DEFAULT 'pending', "is_active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_bc1bf63498dd2368ce3dc8686e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bc1bf63498dd2368ce3dc8686e" ON "yenreach"."businesses" ("id") `);
        await queryRunner.query(`CREATE TABLE "yenreach"."users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "verify_string" character varying(255) NOT NULL, "name" character varying(1000) NOT NULL, "email" character varying(255) NOT NULL, "password" character varying(255) NOT NULL, "profile_image" character varying(255), "referral" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "email_verified" boolean NOT NULL DEFAULT false, "curriculum_vitae" character varying(250), "date_of_birth" character varying(250), "phone_number" character varying(250), "gender" character varying(250), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a3ffb1c0c8416b9fc6f907b743" ON "yenreach"."users" ("id") `);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "yenreach"."users" ("email") `);
        await queryRunner.query(`CREATE TYPE "yenreach"."admins_authorization_level_enum" AS ENUM('staff', 'manager', 'owner')`);
        await queryRunner.query(`CREATE TABLE "yenreach"."admins" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "username" character varying(100) NOT NULL, "password" character varying(200) NOT NULL, "personal_email" character varying(200) NOT NULL, "official_email" character varying(200) NOT NULL, "phone_number" character varying(200) NOT NULL, "authorization_level" "yenreach"."admins_authorization_level_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_4ba6d0c734d53f8e1b2e24b6c56" UNIQUE ("username"), CONSTRAINT "UQ_6628bddf00abd448fb2ed2da819" UNIQUE ("personal_email"), CONSTRAINT "UQ_a715d84eac99271d91376a3e586" UNIQUE ("official_email"), CONSTRAINT "UQ_3a22cd242f3c1fbafa7840a4aaa" UNIQUE ("phone_number"), CONSTRAINT "PK_e3b38270c97a854c48d2e80874e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "yenreach"."job_tags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "job_id" uuid NOT NULL, "tag" character varying(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_a778251317883a9b316fffcb62a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "yenreach"."jobs_status_enum" AS ENUM('open', 'closed', 'filled')`);
        await queryRunner.query(`CREATE TABLE "yenreach"."jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid, "job_string" character varying(255) NOT NULL, "admin_id" uuid, "company_name" character varying(255) NOT NULL, "tittle" character varying(255) NOT NULL, "type" character varying(355) NOT NULL, "location" character varying(255) NOT NULL, "salary" character varying(255) NOT NULL, "description" text NOT NULL, "benefits" text NOT NULL, "status" "yenreach"."jobs_status_enum" NOT NULL, "is_admin_job" boolean NOT NULL DEFAULT false, "application_method" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_cf0a6c42b72fcc7f7c237def345" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6866bb3c271a60ec9156aa8456" ON "yenreach"."jobs" ("business_id") `);
        await queryRunner.query(`CREATE TYPE "yenreach"."feedbacks_status_enum" AS ENUM('pending', 'acknowledged')`);
        await queryRunner.query(`CREATE TABLE "yenreach"."feedbacks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "subject" character varying(255) NOT NULL, "message" text NOT NULL, "status" "yenreach"."feedbacks_status_enum" NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_79affc530fdd838a9f1e0cc30be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "yenreach"."blogs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "author_id" uuid NOT NULL, "tittle" character varying(500) NOT NULL, "preview" text NOT NULL, "media_url" character varying(200) NOT NULL, "content" text NOT NULL, "is_featured" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_e113335f11c926da929a625f118" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "yenreach"."comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "author_id" uuid NOT NULL, "blog_id" uuid NOT NULL, "content" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "yenreach"."saved_business" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "user_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_122e713cfb6e516830b7c0c7026" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "yenreach"."local_governments" ADD CONSTRAINT "FK_a045d924f8ebb9a5334575716ff" FOREIGN KEY ("state_id") REFERENCES "yenreach"."states"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yenreach"."product_photos" ADD CONSTRAINT "FK_ef0be6cd13fe604b1e7ae5987b8" FOREIGN KEY ("product_id") REFERENCES "yenreach"."products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yenreach"."products" ADD CONSTRAINT "FK_6706ea94d32be01f9272ccc3512" FOREIGN KEY ("business_id") REFERENCES "yenreach"."businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yenreach"."product_categories" ADD CONSTRAINT "FK_8748b4a0e8de6d266f2bbc877f6" FOREIGN KEY ("product_id") REFERENCES "yenreach"."products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yenreach"."product_categories" ADD CONSTRAINT "FK_9148da8f26fc248e77a387e3112" FOREIGN KEY ("category_id") REFERENCES "yenreach"."categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yenreach"."categories" ADD CONSTRAINT "FK_de08738901be6b34d2824a1e243" FOREIGN KEY ("parent_category_id") REFERENCES "yenreach"."categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yenreach"."business_categories" ADD CONSTRAINT "FK_3fe5d59ab83736065a0dd5e38a0" FOREIGN KEY ("business_id") REFERENCES "yenreach"."businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yenreach"."business_categories" ADD CONSTRAINT "FK_85bf37fef50a1636fe9ebe4822d" FOREIGN KEY ("category_id") REFERENCES "yenreach"."categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yenreach"."business_photos" ADD CONSTRAINT "FK_8f15fc3faea20619b61ad9d0dfe" FOREIGN KEY ("business_id") REFERENCES "yenreach"."businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yenreach"."business_reviews" ADD CONSTRAINT "FK_86f38bc84d82e2c985d2afe128d" FOREIGN KEY ("business_id") REFERENCES "yenreach"."businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yenreach"."business_videos" ADD CONSTRAINT "FK_39550c1d974cf4a9fcf15efb2ec" FOREIGN KEY ("business_id") REFERENCES "yenreach"."businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yenreach"."business_working_hours" ADD CONSTRAINT "FK_ac12abaae569edd6bf385962efd" FOREIGN KEY ("business_id") REFERENCES "yenreach"."businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yenreach"."businesses" ADD CONSTRAINT "FK_cbb98c2d1e4c7bdf6eabc305c42" FOREIGN KEY ("user_id") REFERENCES "yenreach"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yenreach"."businesses" ADD CONSTRAINT "FK_5e0e4dfadd118393f244dd16c3c" FOREIGN KEY ("state_id") REFERENCES "yenreach"."states"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yenreach"."businesses" ADD CONSTRAINT "FK_a6f23b8a283a270264019304bdd" FOREIGN KEY ("lga_id") REFERENCES "yenreach"."local_governments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yenreach"."job_tags" ADD CONSTRAINT "FK_6bb03bb84ba027d83e0fe2ab397" FOREIGN KEY ("job_id") REFERENCES "yenreach"."jobs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yenreach"."jobs" ADD CONSTRAINT "FK_6866bb3c271a60ec9156aa84569" FOREIGN KEY ("business_id") REFERENCES "yenreach"."businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yenreach"."jobs" ADD CONSTRAINT "FK_2ec1a8e645bee4a808820245494" FOREIGN KEY ("admin_id") REFERENCES "yenreach"."admins"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yenreach"."blogs" ADD CONSTRAINT "FK_b324119dcb71e877cee411f7929" FOREIGN KEY ("author_id") REFERENCES "yenreach"."admins"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yenreach"."comments" ADD CONSTRAINT "FK_6754bf738cb68004be154e1d1d5" FOREIGN KEY ("blog_id") REFERENCES "yenreach"."blogs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yenreach"."comments" ADD CONSTRAINT "FK_e6d38899c31997c45d128a8973b" FOREIGN KEY ("author_id") REFERENCES "yenreach"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yenreach"."saved_business" ADD CONSTRAINT "FK_11c464d65409de55a3c9cdabbbd" FOREIGN KEY ("business_id") REFERENCES "yenreach"."businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yenreach"."saved_business" ADD CONSTRAINT "FK_8fc4fc88f23ba90401c2e05b3aa" FOREIGN KEY ("user_id") REFERENCES "yenreach"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "yenreach"."saved_business" DROP CONSTRAINT "FK_8fc4fc88f23ba90401c2e05b3aa"`);
        await queryRunner.query(`ALTER TABLE "yenreach"."saved_business" DROP CONSTRAINT "FK_11c464d65409de55a3c9cdabbbd"`);
        await queryRunner.query(`ALTER TABLE "yenreach"."comments" DROP CONSTRAINT "FK_e6d38899c31997c45d128a8973b"`);
        await queryRunner.query(`ALTER TABLE "yenreach"."comments" DROP CONSTRAINT "FK_6754bf738cb68004be154e1d1d5"`);
        await queryRunner.query(`ALTER TABLE "yenreach"."blogs" DROP CONSTRAINT "FK_b324119dcb71e877cee411f7929"`);
        await queryRunner.query(`ALTER TABLE "yenreach"."jobs" DROP CONSTRAINT "FK_2ec1a8e645bee4a808820245494"`);
        await queryRunner.query(`ALTER TABLE "yenreach"."jobs" DROP CONSTRAINT "FK_6866bb3c271a60ec9156aa84569"`);
        await queryRunner.query(`ALTER TABLE "yenreach"."job_tags" DROP CONSTRAINT "FK_6bb03bb84ba027d83e0fe2ab397"`);
        await queryRunner.query(`ALTER TABLE "yenreach"."businesses" DROP CONSTRAINT "FK_a6f23b8a283a270264019304bdd"`);
        await queryRunner.query(`ALTER TABLE "yenreach"."businesses" DROP CONSTRAINT "FK_5e0e4dfadd118393f244dd16c3c"`);
        await queryRunner.query(`ALTER TABLE "yenreach"."businesses" DROP CONSTRAINT "FK_cbb98c2d1e4c7bdf6eabc305c42"`);
        await queryRunner.query(`ALTER TABLE "yenreach"."business_working_hours" DROP CONSTRAINT "FK_ac12abaae569edd6bf385962efd"`);
        await queryRunner.query(`ALTER TABLE "yenreach"."business_videos" DROP CONSTRAINT "FK_39550c1d974cf4a9fcf15efb2ec"`);
        await queryRunner.query(`ALTER TABLE "yenreach"."business_reviews" DROP CONSTRAINT "FK_86f38bc84d82e2c985d2afe128d"`);
        await queryRunner.query(`ALTER TABLE "yenreach"."business_photos" DROP CONSTRAINT "FK_8f15fc3faea20619b61ad9d0dfe"`);
        await queryRunner.query(`ALTER TABLE "yenreach"."business_categories" DROP CONSTRAINT "FK_85bf37fef50a1636fe9ebe4822d"`);
        await queryRunner.query(`ALTER TABLE "yenreach"."business_categories" DROP CONSTRAINT "FK_3fe5d59ab83736065a0dd5e38a0"`);
        await queryRunner.query(`ALTER TABLE "yenreach"."categories" DROP CONSTRAINT "FK_de08738901be6b34d2824a1e243"`);
        await queryRunner.query(`ALTER TABLE "yenreach"."product_categories" DROP CONSTRAINT "FK_9148da8f26fc248e77a387e3112"`);
        await queryRunner.query(`ALTER TABLE "yenreach"."product_categories" DROP CONSTRAINT "FK_8748b4a0e8de6d266f2bbc877f6"`);
        await queryRunner.query(`ALTER TABLE "yenreach"."products" DROP CONSTRAINT "FK_6706ea94d32be01f9272ccc3512"`);
        await queryRunner.query(`ALTER TABLE "yenreach"."product_photos" DROP CONSTRAINT "FK_ef0be6cd13fe604b1e7ae5987b8"`);
        await queryRunner.query(`ALTER TABLE "yenreach"."local_governments" DROP CONSTRAINT "FK_a045d924f8ebb9a5334575716ff"`);
        await queryRunner.query(`DROP TABLE "yenreach"."saved_business"`);
        await queryRunner.query(`DROP TABLE "yenreach"."comments"`);
        await queryRunner.query(`DROP TABLE "yenreach"."blogs"`);
        await queryRunner.query(`DROP TABLE "yenreach"."feedbacks"`);
        await queryRunner.query(`DROP TYPE "yenreach"."feedbacks_status_enum"`);
        await queryRunner.query(`DROP INDEX "yenreach"."IDX_6866bb3c271a60ec9156aa8456"`);
        await queryRunner.query(`DROP TABLE "yenreach"."jobs"`);
        await queryRunner.query(`DROP TYPE "yenreach"."jobs_status_enum"`);
        await queryRunner.query(`DROP TABLE "yenreach"."job_tags"`);
        await queryRunner.query(`DROP TABLE "yenreach"."admins"`);
        await queryRunner.query(`DROP TYPE "yenreach"."admins_authorization_level_enum"`);
        await queryRunner.query(`DROP INDEX "yenreach"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "yenreach"."IDX_a3ffb1c0c8416b9fc6f907b743"`);
        await queryRunner.query(`DROP TABLE "yenreach"."users"`);
        await queryRunner.query(`DROP INDEX "yenreach"."IDX_bc1bf63498dd2368ce3dc8686e"`);
        await queryRunner.query(`DROP TABLE "yenreach"."businesses"`);
        await queryRunner.query(`DROP TYPE "yenreach"."businesses_registration_status_enum"`);
        await queryRunner.query(`DROP INDEX "yenreach"."IDX_ac12abaae569edd6bf385962ef"`);
        await queryRunner.query(`DROP TABLE "yenreach"."business_working_hours"`);
        await queryRunner.query(`DROP INDEX "yenreach"."IDX_39550c1d974cf4a9fcf15efb2e"`);
        await queryRunner.query(`DROP TABLE "yenreach"."business_videos"`);
        await queryRunner.query(`DROP INDEX "yenreach"."IDX_86f38bc84d82e2c985d2afe128"`);
        await queryRunner.query(`DROP TABLE "yenreach"."business_reviews"`);
        await queryRunner.query(`DROP INDEX "yenreach"."IDX_8f15fc3faea20619b61ad9d0df"`);
        await queryRunner.query(`DROP TABLE "yenreach"."business_photos"`);
        await queryRunner.query(`DROP TABLE "yenreach"."business_categories"`);
        await queryRunner.query(`DROP TABLE "yenreach"."categories"`);
        await queryRunner.query(`DROP TYPE "yenreach"."categories_category_type_enum"`);
        await queryRunner.query(`DROP TABLE "yenreach"."product_categories"`);
        await queryRunner.query(`DROP INDEX "yenreach"."IDX_6706ea94d32be01f9272ccc351"`);
        await queryRunner.query(`DROP INDEX "yenreach"."IDX_0806c755e0aca124e67c0cf6d7"`);
        await queryRunner.query(`DROP TABLE "yenreach"."products"`);
        await queryRunner.query(`DROP TYPE "yenreach"."products_status_enum"`);
        await queryRunner.query(`DROP INDEX "yenreach"."IDX_ef0be6cd13fe604b1e7ae5987b"`);
        await queryRunner.query(`DROP TABLE "yenreach"."product_photos"`);
        await queryRunner.query(`DROP TABLE "yenreach"."states"`);
        await queryRunner.query(`DROP TABLE "yenreach"."local_governments"`);
    }

}
